lib/chat_web/router.ex
defmodule ChatWeb.Router do
  use ChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChatWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :graphql do
    plug ChatWeb.Plug.Context
    plug :fetch_session
    plug :fetch_flash
  end

  scope "/", ChatWeb do
    pipe_through :browser

    get "/", SessionController, :index
    resources("/rooms", RoomController)
    resources("/sessions", SessionController, only: [:new, :create, :index, :edit, :update])
    resources("/registration", RegistrationController, only: [:new, :create])
    delete "/sign_out", SessionController, :delete

  end

  scope "/api" do
    pipe_through :graphql
    #forward "/", Absinthe.Plug, schema: ChatWeb.Schema
    forward "/graphiql", Absinthe.Plug.GraphiQL, schema: ChatWeb.Schema
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatWeb do
  #   pipe_through :api
  # end
end

lib/chat/session/session_resolver.ex
defmodule Chat.Session.SessionResolver do
  alias Chat.Accounts

  def new(%{:email => email, :password => password}, _info) do
    with {:ok, user} <- Accounts.sign_in(email, password),
         {:ok, jwt, _} <- Chat.Guardian.encode_and_sign(user) do
      {:ok, %{token: jwt}}
    else
      _ -> {:error, "Issue with email or password"}
    end
  end
end

lib/chat_web/controllers/session_controller.ex
defmodule ChatWeb.SessionController do
  use ChatWeb, :controller

  alias Chat.Accounts
  def new(conn, _) do
    render(conn, "new.html")
  end

  def index(conn, _) do

    render(conn, "index.html", edit: nil)
  end

  def create(conn, %{"session" => %{"email" => email, "password" => password}}) do
    case Accounts.sign_in(email, password) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "Sign In Successful")
        |> redirect(to: Routes.room_path(conn, :index))

      {:error, _} ->
        conn
        |> put_flash(:error, "Invalid Email or Password")
        |> render("new.html")
    end

  end

  def edit(conn, _params) do

    user = Accounts.current_user(conn)
    changeset = Accounts.change_user(user)
    render(conn, "index.html", changeset: changeset, edit: 1)
  end

  def update(conn, %{"user" => user_params}) do
    inspect(conn)
    user = Accounts.current_user(conn)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User Updated!")
        |> redirect(to: Routes.session_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "index.html", edit: 1, changeset: changeset)
    end
  end
  def delete(conn, _params) do

    conn
    |> Accounts.sign_out(conn)
    |> redirect(to: Routes.session_path(conn, :index))
  end
end

lib/chat_web/views/session_view.ex
defmodule ChatWeb.SessionView do
  use ChatWeb, :view
end

lib/chat_web/templates/session/index.html.eex
    <div class="bg-indigo-600 rounded-lg h-full w-full flex flex-row px-24 py-48 justify-center content-center relative">
        <%= if @signed_in? do %>
            <a href="<%= Routes.room_path(@conn, :index) %>"><i class="fas fa-arrow-circle-left absolute text-bg text-5xl back-icon"></i></a>

            <div class="mx-24 border-2 rounded-lg border-bg flex flex-row w-full h-full">

                <div class="flex flex-col  w-1/3 h-full">
                <div class="flex flex-row h-56 w-full justify-center  ">
                    <div class="flex flex-col w-90 pt-8 border-b border-bg">
                        <div class="text-5xl font-semibold text-bg ml-4">Welcome,</div>
                        <div class="text-4xl pt-2 text-bg ml-32"><%= @current_user.username %></div>
                    </div>


                    <!-- %= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :delete, class: "btn bg w-1/5 mx-auto mt-4 py-4 align-middle text-indigo-600 rounded-lg text-2xl"  %-->
                </div>
                <ul class="w-full -mt-1 flex-grow">
                    <li class="m-0 lg:text-3xl text-2xl rounded-r-lg">
                        <a href="<%= Routes.session_path(@conn, :edit, @current_user.id) %>" class="h-full w-full ">
                            <div class="py-8 pl-16 ">
                                <i class="fas fa-user-circle mr-8 "></i> Account Info
                            </div>
                        </a>
                    </li>
                    <li class="m-0 lg:text-3xl text-2xl rounded-r-lg">
                        <a href="" class="h-full w-full ">
                            <div class="py-8 pl-16 ">
                                <i class="fas fa-users mr-8 "></i> Friends
                            </div>
                        </a>
                    </li>
                    <li class="m-0 lg:text-3xl text-2xl rounded-r-lg">
                        <a href="" class="h-full w-full ">
                            <div class="py-8 pl-16 ">
                                <i class="fas fa-flask mr-8 "></i> Settings
                            </div>
                        </a>
                    </li>
                </ul>
                <div class="m-0 lg:text-3xl text-2xl rounded-r-lg li-hover">
                        <a href="<%= Routes.session_path(@conn, :delete) %>" data-method="delete" data-csrf="<%= Phoenix.Controller.get_csrf_token()%>" data-to="<%= Routes.session_path(@conn, :delete) %>" class="h-full w-full ">
                            <div class="py-8 pl-16 ">
                                <i class="fas fa-sign-out-alt mr-8 "></i> Log Out
                            </div>
                        </a>
                </div>
            </div>
            <div class="flex flex-col w-2/3 h-full justify-center py-24">
                <div class="w-4/5 h-full rounded-lg bg shadow-md mx-auto px-8 py-12 flex flex-col justify-around">
                <%= if @edit do %>
                <h1 class="text-indigo-600 text-4xl font-black">Update Your Account Information</h1>
                <%= form_for @changeset, Routes.session_path(@conn, :update, @current_user.id), [as: :user], fn f -> %>
                    <div class="form-group flex flex-col w-4/5 mx-auto">
                        <%= label f, :email, class: "control-label text-indigo-600" %>
                        <%= text_input f, :email, class: "text-xl input-alt   ", placeholder: "Email", required: true, autofocus: true  %>
                        <%= error_tag f, :email %>
                    </div>

                    <div class="form-group flex flex-col w-4/5 mx-auto">
                        <%= label f, :username, class: "control-label text-indigo-600" %>
                        <%= text_input f, :username, class: "text-xl input-alt  ", placeholder: "Username", required: true, autofocus: true  %>
                        <%= error_tag f, :username %>
                    </div>

                    <div class="form-group flex flex-col w-4/5 mx-auto">
                        <%= label f, :password, class: "control-label text-indigo-600"  %>
                        <%= password_input f, :password, class: "text-xl input-alt  ", placeholder: "Password", required: true  %>
                        <%= error_tag f, :password  %>
                    </div>

                    <div class="form-group flex flex-col w-4/5 mx-auto">
                        <%= label f, :password_confirmation, class: "control-label text-indigo-600"  %>
                        <%= password_input f, :password_confirmation, class: "text-xl input-alt ", placeholder: "Re-Enter Password", required: true  %>
                        <%= error_tag f, :password_confirmation  %>
                    </div>

                    <div class="flex flex-row mt-8 w-full justify-center">
                        <%= submit "Update.", class: "btn-alt btn text-bg green h-16 rounded-lg font-semibold text-2xl bg w-1/3" %>

                    </div>

                    <% end %>
                <% else %>
                    <div class="text-indigo-600 text-6xl text-center font-black">Welcome to Your Profile Page.</div>
                    <div class="text-indigo-600 text-4xl mt-12 px-4 flex flex-row"><i class="fas fa-tasks mr-12 text-5xl my-auto "></i><p>Here is where you will manage all aspects of your account.</p></div>
                    <div class="text-indigo-600 text-4xl mt-12 px-4 flex flex-row"><i class="far fa-check-circle mr-12 text-5xl my-auto "></i><p>To get started, select an option from the menu on the left.</p></div>
                </div>
                <% end %>
            </div>
            </div>


        <% else %>
        <h1 class="text-6xl font-semibold text-center">Welcome to Chat App.</h1>
        <h4 class="text-4xl font-normal mt-4 text-center">Sign In or Register to start chatting!</h4>
        <div class="flex flex-row w-2/5 justify-between mx-auto mt-8">

        <a class="btn bg w-2/5 mx-auto mt-4 h-24 pt-4 text-indigo-600 rounded-lg text-3xl font-semibold green" href="<%= Routes.session_path(@conn, :new) %> ">Sign In.</a>
        <a class="btn bg w-2/5 mx-auto mt-4 h-24 pt-4 text-indigo-600 rounded-lg text-3xl font-semibold green" href="<%= Routes.registration_path(@conn, :new) %> ">Register.</a>
        </div>

        <% end %>
    </div>

lib/chat_web/templates/session/new.html.eex
    <div class="bg-indigo-600 rounded-lg h-full w-full flex flex-col justify-center content-center px-24 relative">
    <a href="<%= Routes.session_path(@conn, :index) %>"><i class="fas fa-arrow-circle-left absolute text-bg text-5xl back-icon"></i></a>

        <h1 class="text-6xl font-semibold text-center text-bg">Sign In.</h1>

        <%= form_for @conn, Routes.session_path(@conn, :create), [as: :session], fn f -> %>
        <div class="form-group flex flex-col w-1/3 mx-auto">
            <%= label f, :email, class: "control-label text-bg" %>
            <%= text_input f, :email, class: "  input text-white  ", placeholder: "Email", required: true, autofocus: true  %>
            <%= error_tag f, :email %>
        </div>

        <div class="form-group flex flex-col w-1/3 mx-auto">
            <%= label f, :password, class: "control-label text-bg"  %>
            <%= password_input f, :password, class: "  input text-white ", placeholder: "Password", required: true  %>
            <%= error_tag f, :password  %>
        </div>
        <div class="flex flex-row mt-8 w-1/3 mx-auto justify-center">
            <%= submit "Go.", class: "btn green text-indigo-600 h-16 rounded-lg font-semibold text-2xl bg w-1/3" %>

        </div>

        <% end %>
    </div>