lib/chat_web/router.ex
defmodule ChatWeb.Router do
  use ChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChatWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :graphql do
    plug ChatWeb.Plug.Context
    plug :fetch_session
    plug :fetch_flash
  end

  scope "/", ChatWeb do
    pipe_through :browser

    get "/", SessionController, :index
    resources("/rooms", RoomController)
    resources("/sessions", SessionController, only: [:new, :create, :index, :edit, :update])
    resources("/registration", RegistrationController, only: [:new, :create])
    delete "/sign_out", SessionController, :delete

  end

  scope "/api" do
    pipe_through :graphql
    #forward "/", Absinthe.Plug, schema: ChatWeb.Schema
    forward "/graphiql", Absinthe.Plug.GraphiQL, schema: ChatWeb.Schema
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatWeb do
  #   pipe_through :api
  # end
end

lib/chat/room/room_resolver.ex
defmodule Chat.Room.RoomResolver do
  alias Chat.Talk

  alias Chat.Accounts

  def all(_args, _info) do
    {:ok, Talk.list_rooms()}
  end

  def create(%{:name => name, :description => description, :topic => topic}, %{
        :context => %{:user_id => user_id}
      }) do
    user = Accounts.get_user!(user_id)

    case Talk.create_room(user, %{name: name, description: description, topic: topic}) do
      {:ok, room} -> {:ok, room}
      {:error, _changeset} -> {:error, "Something went wrong with your room"}
    end
  end
end

lib/chat/talk/room.ex
defmodule Chat.Talk.Room do
  use Ecto.Schema
  import Ecto.Changeset
  alias Chat.Talk.Room
  schema "rooms" do
    field :description, :string
    field :name, :string
    field :topic, :string
    belongs_to :user, Chat.Accounts.User
    has_many :messages, Chat.Talk.Message

    timestamps()
  end

  @doc false
  def changeset(%Room{} = room, attrs) do
    room
    |> cast(attrs, [:name, :description, :topic])
    |> validate_required([:name])
    |> unique_constraint(:name)
    |> validate_length(:name, min: 1, max: 30)
    |> validate_length(:topic, min: 1, max: 120)
  end
end

lib/chat_web/controllers/room_controller.ex
defmodule ChatWeb.RoomController do
  use ChatWeb, :controller

  alias Chat.Talk.Room
 
  alias Chat.Talk

  plug ChatWeb.Plugs.AuthUser when action in [:new, :create, :show, :edit, :update, :delete, :index]
  plug :authorize_user when action in [:edit, :update, :delete]
  def index(conn, _params) do
    rooms = Talk.list_rooms()
    render(conn, "index.html", rooms: rooms, activeroom: nil, edit: nil, create: nil)
  end

  def new(conn, _params) do
    rooms = Talk.list_rooms()
    changeset = Room.changeset(%Room{}, %{})
    render(conn, "index.html", changeset: changeset, rooms: rooms, create: 1, edit: nil, activeroom: nil)
  end

  def create(conn, %{"room" => room_params}) do
    rooms = Talk.list_rooms()
    case Talk.create_room(conn.assigns.current_user, room_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Room Created!")
        |> redirect(to: Routes.room_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "index.html", changeset: changeset, rooms: rooms, create: 1, edit: nil, activeroom: nil)

    end
  end
  def show(conn, %{"id" => id}) do
    activeroom = Talk.get_room!(id)
    rooms = Talk.list_rooms()
    render(conn, "index.html", rooms: rooms, activeroom: activeroom, edit: nil)
  end

  def edit(conn, %{"id" => id}) do
    room = Talk.get_room!(id)
    changeset = Talk.change_room(room)
    rooms = Talk.list_rooms()
    render(conn, "index.html", rooms: rooms, activeroom: room, edit: 1, changeset: changeset)
  end

  def update(conn, %{"id" => id, "room" => room_params}) do
    room = Talk.get_room!(id)
    rooms = Talk.list_rooms()
    case Talk.update_room(room, room_params) do
      {:ok, room} ->
        conn
        |> put_flash(:info, "Room Updated!")
        |> redirect(to: Routes.room_path(conn, :show, id))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "index.html", rooms: rooms, activeroom: room, edit: 1, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    room = Talk.get_room!(id)
    {:ok, _room} = Talk.delete_room(room)

    conn
    |> put_flash(:info, "Room deleted")
    |> redirect(to: Routes.room_path(conn, :index))
  end

  defp authorize_user(conn, _params) do
    %{params: %{"id" => room_id}} = conn
    room = Talk.get_room!(room_id)

    if conn.assigns.current_user.id == room.user_id do
      conn
    else
      conn
      |> put_flash(:error, "Unauthorized")
      |> redirect(to: Routes.room_path(conn, :show, room_id))
      |> halt()
    end
  end

end

lib/chat_web/views/room_view.ex
defmodule ChatWeb.RoomView do
  use ChatWeb, :view
end

lib/chat_web/templates/room/index.html.eex
    <div class="col-md-3 bg-indigo-600 text-bg   h-full rounded-l-lg  " style="padding-left: 0 !important; padding-right: 0 !important;">
        <%= if @signed_in? do %>
            <div class="h-24  rounded-tl-lg flex flex-row mb-2 justify-around border-b border-bg w-90 mx-auto ">
            <div class="rounded-full h-12 w-12 lg:h-16 lg:w-16 flex items-center justify-center bg my-auto lg:ml-4 text-indigo-600" id="user-acct">
                <a href="<%= Routes.session_path(@conn, :index) %>" class=" h-12 w-12lg:h-16 lg:w-16 lg:text-2xl text-xl flex items-center justify-center rounded-full">
                    <i class="fas fa-user"></i>
                </a>
            </div>
            <div class="flex flex-col lg:ml-4 mt-2  w-2/3 lg:text-3xl text-2xl">
                <div class="font-semibold ">Welcome,</div>
                <div class="lg:ml-16 ml-4 -mt-2 "><%= @current_user.username%></div>
            </div>

                <!-- h1 class="text-4xl text-bg">Welcome <%= link @current_user.username, to: Routes.session_path(@conn, :index), class: "text-bg"  %></h1 -->
            </div>
        <% end %>
        <%= link "Rooms", to: Routes.room_path(@conn, :index), class: "lg:text-4xl text-3xl font-bold ml-8 text-bg" %>
        <ul class="mt-2 w-full">
        <%= for room <- @rooms do %>
            <li class="m-0 lg:text-3xl text-2xl">
                <a href="<%= Routes.room_path(@conn, :show, room.id) %>" class="h-full w-full ">
                    <div class="py-8 pl-16 ">
                        <i class="fas fa-door-closed mr-8 "></i> <%= room.name %>
                    </div>
                </a>
            </li>
        <% end %>
        </ul>
    </div>
    <div class="col-md-9 p-0 h-full shadow-inner">
        <div class="jumbotron text-center text-gray-500 flex flex-col h-full rounded-l-none main-accent m-0 relative pt-24 pb-0 overflow-x-hidden">
            <%= if @activeroom do %>
                <%= if @edit do %>
                    <h2 class="text-5xl font-bold text-white">Edit <%= @activeroom.name %> </h2>
                    <%= form_for @changeset, Routes.room_path(@conn, :update, @activeroom.id), fn f -> %>
                    <div class="form-group mx-auto">
                        <%= label f, :name, class: "control-label text-white" %>
                        <%= text_input f, :name, class: " w-1/3 text-white text-3xl input"  %>
                        <%= error_tag f, :name %>
                    </div>

                    <div class="form-group">
                        <%= label f, :topic, class: "control-label text-white"  %>
                        <%= text_input f, :topic, class: " w-1/3 text-white text-3xl input"  %>
                        <%= error_tag f, :topic  %>
                    </div>

                    <div class="form-group">
                        <%= label f, :description, class: "control-label text-white"  %>
                        <%= text_input f, :description, class: " w-1/3 text-white text-3xl input"  %>
                        <%= error_tag f, :description %>
                    </div>
                    <div class="flex flex-col mt-4 w-full">
                        <%= submit "Update", class: "btn text-white text-xl bg-indigo-600 w-1/3 mt-4 mx-auto" %>
                        <%= link "Delete", to: Routes.room_path(@conn, :delete, @activeroom), method: :delete, class: "btn mx-auto text-white bg-red-600 mt-4 text-xl py-2 w-1/3"  %>
                    </div>

                    <% end %>

                <% else %>
                    <nav class="bg-indigo-600 h-24 w-full absolute top-0 left-0 nav-shadow rounded-tr-lg flex flex-row justify-between p-4 animated slideInLeft">
                        <h1 class="text-3xl lg:text-4xl font-semibold text-bg  pl-4"><%= @activeroom.name %> : <span class="font-normal"><%= @activeroom.description %></span></h1>
                        <div class="flex lg:text-3xl text-2xl my-auto flex-row w-1/4 text-bg justify-between">
                            <div class="flex flex-row w-1/3 ">
                                <a href="<%= Routes.room_path(@conn, :edit, @activeroom.id) %>" class="green-a"><i class="fas fa-edit"></i></a>

                            </div>
                            <div class="flex flex-row w-1/3 "> <a href="<%= Routes.room_path(@conn, :index) %>" class="back-icon"><i class="fas fa-arrow-circle-left"></i></a></div>
                            <div class="flex flex-row w-1/3  tt ">
                                <div id="user-names" class="tooltiptext tooltip-bottom text-2xl p-4 font-semibold"></div>
                                <i class="fas fa-users"></i>
                                <div id="user-count" class="font-semibold ml-2"></div>
                            </div>
                        </div>
                    </nav>
                    <div class="flex flex-col h-full slideInLeft animated">
                        <ul class="list-group flex-grow mt-2 flex-col-reverse overflow-y-scroll" id="display"></ul>
                        <div class=" self-end flex flex-col w-full">
                            <form class="input-group mb-0 mt-2 " id="message-form">

                                <input type="text" class="input text-white w-4/5" id="message-body" placeholder="Message for # <%= @activeroom.name %>" autocomplete="off">
                                <div class="input-group-append w-1/5">
                                    <button class="btn text-3xl text-white font-semibold w-full bg-green-500" id="message-button"><i class="fas fa-paper-plane"></i></button>
                                </div>
                            </form>
                            <div id="user-typing" class="m-0 ml-2 h-8 max-h-8 text-xl text-left"></div>

                        </div>
                    </div>
                    <script>window.roomId = "<%= @activeroom.id %>"</script>

                <% end %>
                <% else %>
                <%= if @create do %>
                    <h2 class="text-5xl font-bold text-second-accent mb-8">Add A New Room.</h2>
                    <%= form_for @changeset, Routes.room_path(@conn, :create), fn f -> %>
                    <div class="form-group flex flex-col w-1/3 mx-auto">
                        <%= label f, :name, class: "control-label text-second-accent" %>
                        <%= text_input f, :name, class: "input text-white"  %>
                        <%= error_tag f, :name %>
                    </div>

                    <div class="form-group flex flex-col w-1/3 mx-auto">
                        <%= label f, :topic, class: "control-label text-second-accent"  %>
                        <%= text_input f, :topic, class: "input text-white"  %>
                        <%= error_tag f, :topic  %>
                    </div>

                    <div class="form-group flex flex-col w-1/3 mx-auto">
                        <%= label f, :description, class: "control-label text-second-accent"  %>
                        <%= text_input f, :description, class: "input text-white"  %>
                        <%= error_tag f, :description %>
                    </div>
                    <div class="flex flex-row mt-8 w-1/3 mx-auto justify-center">
                        <%= submit "Create.", class: "btn green text-second-accent h-16 rounded-lg font-semibold text-2xl bg w-2/3" %>
                    </div>
                    <% end %>
                <% else %>
                <div class="text-second-accent h-full flex justify-center content-center flex-col animated fadeIn">
                <h1 class="text-6xl font-semibold">Welcome to Chat App</h1>
                <h4 class="text-4xl font-normal mt-2">Join a room or create one</h4>
                <a class="btn bg w-1/5 mx-auto mt-4 py-4 align-middle text-second-accent rounded-lg text-2xl" href="<%= Routes.room_path(@conn, :new) %> ">Create a Room</a>
                </div>
                <% end %>
            <% end %>
        </div>
    </div>

lib/chat_web/templates/room/new.html.eex
<h2 class="text-5xl font-bold text-white">Add new room</h2>

<%= form_for @changeset, Routes.room_path(@conn, :create), fn f -> %>
<div class="form-group">
    <%= label f, :name, class: "control-label text-white" %>
    <%= text_input f, :name, class: "form-control"  %>
    <%= error_tag f, :name %>
</div>

<div class="form-group">
    <%= label f, :topic, class: "control-label text-white"  %>
    <%= text_input f, :topic, class: "form-control"  %>
    <%= error_tag f, :topic  %>
</div>

<div class="form-group">
    <%= label f, :description, class: "control-label text-white"  %>
    <%= text_input f, :description, class: "form-control"  %>
    <%= error_tag f, :description %>
</div>
    <%= submit "Create", class: "btn text-white bg-indigo-600 w-1/4" %>
<% end %>